base_url = "https://gburghoorn.com"

title = "GBurghoorn"
description = "Hi!"

default_language = "en"

compile_sass = false

generate_feed = true
feed_filename = "rss.xml"

build_search_index = true
smart_punctuation = true

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-light"

taxonomies = [
    {name = "tags", feed = true}
]

[extra]
keywords = ["computers", "security", "math"]
author = "Gijs Burghoorn"
