base_url = "https://gburghoorn.com"

title = "GBurghoorn"
description = "Hi!"

default_language = "en"

compile_sass = false

build_search_index = true

[markdown]
highlight_code = false

taxonomies = [
    {name = "tags", feed = true}
]

[extra]
keywords = ["computers", "security", "math"]
author = "Gijs Burghoorn"
