# This is a basic workflow to help you get started with Actions
name: Publish to gburghoorn.com

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Publish to gburghoorn.com
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Download and run TailwindCSS
      - name: TailwindCSS Build
      - run: curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.2.4/download/tailwindcss-linux-x64
      - run: chmod +x tailwindcss-linux-x64
      - run: ./tailwindcss-linux-x64 -i styles/styles.scss -o static/styles/styles.css --minify

      # Download and run Zola
      - name: Zola Build
      - run: curl -s -L https://github.com/getzola/zola/releases/download/v0.16.1/zola-v0.16.1-x86_64-unknown-linux-gnu.tar.gz | sudo tar xvzf - -C /usr/local/bin
      - run: zola build

      - name: Copy Files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SCP_HOST }}
          username: ${{ secrets.SCP_USERNAME }}
          key: ${{ secrets.SCP_SSH_KEY }}
          passphrase: ${{ secrets.SCP_SSH_PW }}
          port: ${{ secrets.SCP_PORT }}
          target: ${{ secrets.SCP_PATH }}
          source: "public/*"
          strip_components: 1
